name: Test build

on:
  pull_request:
        types: [opened, reopened]
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for CMSIS update to run
      if: ${{ github.event_name == 'pull_request' }}
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        check-name: 'CMSISUpdate'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
  build:
    needs: wait
    uses: Tellicious/CIActions/.github/workflows/STM32Build.yml@main
    with:
      build-type: Release
      target-branch: ${{ github.head_ref || github.ref_name }}
    secrets:
      pat: ${{ secrets.PAT }}

