name: CMSIS-core driver update

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  CMSISUpdate:
    if: ${{ contains(github.event.pull_request.title, 'Bump Modules/CMSIS') }}
    uses: Tellicious/CIActions/.github/workflows/CMSISCoreUpdate.yml@main
    with:
      target-branch: ${{ github.head_ref || github.ref_name }}
      stm32cube-repo: STM32CubeF1
    secrets:
      pat: ${{ secrets.PAT }}