name: Publish release with build artifacts

on:
  push:
  # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  release:
    uses: Tellicious/CIActions/.github/workflows/STM32PublishRelease.yml@main
    with:
      build-type: Release
      target-branch: ${{ github.ref_name }}
      tag: ${{ github.ref }}
      release-name: ParkingSensor ${{ github.ref_name }}
      body-file: ".github/releaseBody.md"
    secrets:
      pat: ${{ secrets.PAT }}
  

